import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const Wrapper = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: center;
`

const InnerWrapper = styled.div`
  display: flex;
  flex-direction: column;
  padding: 0px 20px;
  width: 800px;
  @media screen and (max-width: 800px) {
    width: 100%;
  }
`

const Title = styled.div`
  font-size: 2.75rem;
  font-weight: 700;
`

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Frontend Dev. JY</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <InnerWrapper>
        <Title>안녕하세요!</Title>
      </InnerWrapper>
    </Wrapper>
  )
}

export default Home
